name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u hind7065 --password-stdin

      - name: Build Docker image
        run: docker build -t hind7065/lab8-app:latest .

      - name: Push Docker image
        run: docker push hind7065/lab8-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/lab8-cicd
            git pull
            docker compose pull
            docker compose down
            docker compose up -d  